Homework 1
thebergamo/angular-mentoring pull request #1
Opened 2018-07-09 17:51 UTC by thebergamo

2018-07-09 21:44 UTC, thebergamo commented
@aledpardo can you take a look :D

2018-07-11 08:24 UTC, aledpardo requested changes
@thebergamo, please do change the classes properties assessor. All the rest seems ok.

2018-07-11 08:24 UTC, aledpardo commented on src/app/Models/CourseModel.ts
> +  id = ''
Consider to define the properties as `public` and add the `;` at end of line.

2018-07-11 08:24 UTC, aledpardo commented on src/app/header/header.component.css
> +  background-color: #106CC8;
Just for curiosity, try to use the new CSS variables to handle colors etc.

2018-07-11 08:24 UTC, aledpardo commented on src/app/header/header.component.css
> +  background-color: #106CC8;
I mean, in future hw

2018-07-11 20:27 UTC, thebergamo commented on src/app/Models/CourseModel.ts
> +  id = ''
done o/

2018-07-11 20:27 UTC, thebergamo commented on src/app/header/header.component.css
> +  background-color: #106CC8;
done o/.

2018-07-20 21:10 UTC, aledpardo approved these changes

2018-07-20 21:10 UTC, merged